### Get all sweets
GET http://localhost:3000/api/sweets

###

### Add a new sweet
POST http://localhost:3000/api/sweets
Content-Type: application/json

{
  "name": "Barfi",
  "price": 15,
  "quantity": 40
}

### Purchase a sweet
POST http://localhost:3000/api/sweets/3/purchase
Content-Type: application/json

{
  "quantity": 5
}
###quantity more than available
POST http://localhost:3000/api/sweets/1/purchase
Content-Type: application/json

{
  "quantity": 1000
}

### testing Restock a sweet
POST http://localhost:3000/api/sweets/1/restock
Content-Type: application/json

{
  "quantity": 20
}

### Delete a sweet
DELETE http://localhost:3000/api/sweets/2
### Delete a sweet out of index
DELETE http://localhost:3000/api/sweets/999

### Register admin
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "username": "admin",
  "password": "admin123",
  "role": "admin"
}

###

### Login admin
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin123"
}

###ADMIN route WITHOUT token
POST http://localhost:3000/api/sweets
Content-Type: application/json

{
  "name": "Kaju Katli",
  "price": 20,
  "quantity": 30
}

### Add sweet as admin (protected)
POST http://localhost:3000/api/sweets
Authorization: Bearer "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzY1NzMxMzgxLCJleHAiOjE3NjU3MzQ5ODF9.s4s_Q2u1ZqHB0eEuqLy9ORsFxugnHc_RArd5JqovNXw"
Content-Type: application/json

{
  "name": "Kaju Katli",
  "price": 20,
  "quantity": 30
}
